name: Terraform Deploy to GCP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./google-cloud-ai  # Set to your project directory

    steps:
    - uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
        terraform_wrapper: false  # Avoids extra output wrapping for cleaner logs

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate  # Adds a validation step to catch syntax errors early

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      if: github.event_name == 'pull_request'

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      if: github.event_name == 'push' && success()  # Only apply if previous steps succeed

