name: Terraform Deploy to GCP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform GCP CI"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform_version: [1.5.0]
    defaults:
      run:
        working-directory: google-cloud-ai
    env:
      GOOGLE_APPLICATION_CREDENTIALS: .gcpneotron-460405-1f9de633812b.json

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Clean nested Git folder
        run: |
          if [ -d "google-cloud-ai/.git" ]; then
            echo "Removing nested .git folder"
            rm -rf google-cloud-ai/.git
          fi

      - name: List project directory
        run: |
          echo "Workspace contents:"
          ls -R .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform_version }}
          terraform_wrapper: false

      - name: Cache Terraform dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.terraform.d/plugin-cache
            google-cloud-ai/.terraform
          key: ${{ runner.os }}-tf-${{ matrix.terraform_version }}-${{ hashFiles('google-cloud-ai/**/*.tf*') }}

      - name: Write GCP credentials
        run: |
          set -euo pipefail
          echo "Writing GCP key to $GOOGLE_APPLICATION_CREDENTIALS"
          echo "${{ secrets.GCP_KEY }}" > "$GOOGLE_APPLICATION_CREDENTIALS"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Run tfsec security scan
        uses: aquasecurity/tfsec@v1.28.1

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: |
          terraform plan -no-color -out=tfplan | tee plan.txt
        continue-on-error: true

      - name: Comment Terraform Plan
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: plan.txt
          header: "### Terraform Plan"

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan

      - name: Upload plan artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: |
            google-cloud-ai/tfplan
            google-cloud-ai/plan.txt

      - name: Clean up credentials file
        if: always()
        run: rm -f "$GOOGLE_APPLICATION_CREDENTIALS"

