name: Terraform Deploy to GCP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform GCP CI"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform_version: [1.5.0]
    defaults:
      run:
        working-directory: .
    env:
      GOOGLE_APPLICATION_CREDENTIALS: google-cloud-ai/gcp-credentials.json  # Mantido como referência, mas não usado diretamente

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Debug working directory
        run: |
          pwd
          ls -la

      - name: Ensure directory exists
        run: mkdir -p google-cloud-ai

      - name: Clean nested Git folder
        run: |
          if [ -d "google-cloud-ai/.git" ]; then
            echo "Removing nested .git folder"
            rm -rf google-cloud-ai/.git
          fi

      - name: List project directory
        run: |
          echo "Workspace contents:"
          ls -R .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform_version }}
          terraform_wrapper: false

      - name: Cache Terraform dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.terraform.d/plugin-cache
            google-cloud-ai/.terraform
          key: ${{ runner.os }}-tf-${{ matrix.terraform_version }}-${{ hashFiles('google-cloud-ai/**/*.tf*') }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Debug GCP credentials setup
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS is set to: $GOOGLE_APPLICATION_CREDENTIALS"
          echo "Note: Actual credentials file may be managed by google-github-actions/auth."

      - name: Terraform Format Check
        run: terraform fmt -check || true

      - name: Terraform Init
        run: terraform init || echo "Terraform init failed, check configuration and credentials"

      - name: Run tfsec security scan
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          additional_args: --concise-output
        continue-on-error: true

      - name: Terraform Validate
        run: terraform validate || true

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: |
          terraform plan -no-color -out=tfplan | tee plan.txt
        continue-on-error: true

      - name: Comment Terraform Plan
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: plan.txt
          header: "### Terraform Plan"

      - name: Terraform Plan (for Apply)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform plan -no-color -out=tfplan || true

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && success()
        run: terraform apply -auto-approve tfplan || echo "Terraform apply failed, check plan output"

      - name: Upload plan artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: |
            google-cloud-ai/tfplan
            google-cloud-ai/plan.txt
        continue-on-error: true

      - name: Clean up credentials file (if any)
        if: always()
        run: |
          echo "Note: google-github-actions/auth manages cleanup of temporary credentials."
          if [ -f "google-cloud-ai/gcp-credentials.json" ]; then
            rm -f "google-cloud-ai/gcp-credentials.json"
            echo "Manual credentials file deleted."
          else
            echo "No manual credentials file found at google-cloud-ai/gcp-credentials.json."
          fi

